# Ignore warnings "Version reference 'X' is not used in build scripts".

[versions]
# Gradle
androidGradlePlugin = "9.2.0"

# Android
compileSdk = "37"
targetSdk = "35"
minSdk = "24"
tools = "32.0.0"

# Kotlin
kotlin = "2.2.21"
ksp = "2.3.8"
java = "18"
coroutines = "1.9.0"
kotlinSerializationPlugin = "1.9.25"
kotlinSerializationCore = "1.9.0"

# AndroidX
androidx-appcompat = "1.7.0"
androidx-lifecycle = "2.8.7"

# Compose
compose-bom = "2025.10.00" # https://developer.android.com/jetpack/compose/bom/bom-mapping
# version of Compose compiler is determined by plugin "org.jetbrains.kotlin.plugin.compose" and is using Kotlin version
# see: https://developer.android.com/develop/ui/compose/compiler

# Dagger & Hilt
hilt = "2.59"
hiltNavigationCompose = "1.2.0"

# Remote
retrofit-library = "2.11.0"
retrofit-moshi = "2.7.0"
okhttp3-loggingInterceptor = "4.12.0"

# Local
dataStore-preferences = "1.1.1"

# Testing
junit = "6.1.0"
mockk = "1.14.9"
kotestAssertions = "5.5.5"
robolectric = "4.16"
robolectricJunit5Ext = "0.9.0"
turbine = "1.2.1"

# Misc (preserve alphabetical order)
aboutLibraries = "14.2.0"
arrow-optics = "2.2.1.1"
jakewhartonTimber = "5.0.1"
mmolosayDebounce = "1.2.0"
valentinilkShimmer = "1.2.0"